
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/rhino.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/rhino.data/configuration"

    # micro service for proxy-rhino-can.
    proxy-rhino-can:
        build: .
        depends_on:
            - odsupercomponent
        network_mode: "host"
        privileged: true
        command: "/opt/opendlv.rhino/bin/opendlv-proxy-rhino-can --cid=${CID} --id=5 --freq=100"

    # micro service for proxy-trimble.
    proxy-trimble:
        build: .
        depends_on:
            - odsupercomponent
        network_mode: "host"
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-trimble --cid=${CID} --id=5"

    # micro service for logic-legacy-vehiclefollower.
    logic-legacy-vehiclefollower:
        build: .
        depends_on:
            - odsupercomponent
        network_mode: "host"
        command: "/opt/opendlv/bin/opendlv-logic-legacy-vehiclefollower --cid=${CID} --verbose=1 --freq=100"
