# docker-compose.yml - Composition of micro-services to run scaled cars software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-09

version: '2'

services:
    # micro service for proxy-trimble.
    proxy-trimble:
        build: .
        network_mode: "host"
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-trimble --cid=${CID}"

    action-setopticalrotation:
        build: .
        network_mode: host
        working_dir: /opt/opendlv.data
        command: "/opt/opendlv/bin/opendlv-logic-action-setopticalrotation --cid=${CID}"


