version: '2'
# Please note that docker-compose does not prescribe a startup order

services:
    #odsupercomponent
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
        
    #odcockpit
    odcockpit:
        build: .
        network_mode: "host"
        ipc: host
        user: odv
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/recordings:/opt/recordings
        - .:/opt/opendlv.data
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"
        
    # micro service for proxy-rhino-can.
    proxy-rhino-can:
        build: .
        network_mode: "host"
        ipc: host
        privileged: true
        depends_on:
          - odsupercomponent
        command: "/opt/opendlv.rhino/bin/opendlv-proxy-rhino-can --cid=${CID} --freq=100"

